id: ADE3EED55
title: The Prayer to Orgyen Rinpoche that Invokes the Heart of his Wisdom Mind
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:15:27.782011
  last_modified_at: 2022-03-01 01:15:27.782019
